### PR TITLE
Fix issue highlighted during testing

### LINKED ISSUE #20: Warn of no vote even if vote is there
Probably to do with abdul's changes

### PR DESCRIPTION
**Pull request by CheAle14**
Close #20

### CODE REVIEW

**Comment by abdulshafiq2002** [comment]
Nope doesnt work - go back to what i did

**Comment by CheAle14** [comment]
Do not close pull requests.

**Comment by CheAle14** [comment]
```
1)type two names and click the button for the first catergory
2)click next
3)vote for 2 people on the nest catergory
4)click previous
problem they are gone
```
Is the issue: prior votes are not properly being set on btnPrevious click

**Comment by abdulshafiq2002** [comment]
Done

**Comment by CheAle14** [comment]
Done in what?
What commit fixed this?
Don't close this again

**Comment by abdulshafiq2002** [comment]
Fixed in commit 9c754f8

**Comment by CheAle14** [comment]
You don't close a pull request to merge the changes

**Comment by CheAle14** [comment]
Either approve the changes or make a comment requesting changes

**Comment by SneakyBoy10** [comment]
I see this change to be fir to be merged

**Review by SneakyBoy10 — APPROVED** [review]

**Pull request merged**
